services:
  - type: web
    name: inreal-backend
    env: node
    plan: free
    repo: https://github.com/hafabdulla/InReal-Demo.git
    branch: main
    buildCommand: "npm install --include=dev"
    startCommand: "node server.postgres.js"
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: DB_SSL
        value: "true"
      - key: API_PORT
        value: "5000"
      - key: NODE_ENV
        value: "production"
      - key: FRONTEND_URL
        value: ""
    healthCheckPath: /api/health
    autoDeploy: true
